-- Canonical mobile account, history and quota schema. Safe to run repeatedly.
begin;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  profile_name text not null default 'Veggie Nutzer',
  display_name text,
  avatar_url text,
  premium_status text not null default 'free'
    check (premium_status in ('free','trialing','active','past_due','canceled')),
  premium_plan text not null default 'free',
  premium_until timestamptz,
  diet_mode text not null default 'vegan',
  warning_ingredients text[] not null default array['milch','ei','gelatine','honig'],
  account_deletion_requested_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles
  add column if not exists email text,
  add column if not exists profile_name text not null default 'Veggie Nutzer',
  add column if not exists display_name text,
  add column if not exists avatar_url text,
  add column if not exists premium_status text not null default 'free',
  add column if not exists premium_plan text not null default 'free',
  add column if not exists premium_until timestamptz,
  add column if not exists diet_mode text not null default 'vegan',
  add column if not exists warning_ingredients text[] not null default array['milch','ei','gelatine','honig'],
  add column if not exists account_deletion_requested_at timestamptz,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();
update public.profiles set display_name=profile_name where display_name is null;

create table if not exists public.user_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  diet_type text not null default 'vegan'
    check (diet_type in ('vegan','vegetarian','flexitarian','no_preference')),
  goal text not null default 'Ich möchte mich pflanzlicher ernähren.',
  allergies text[] not null default '{}',
  excluded_ingredients text[] not null default '{}',
  language text not null default 'de',
  country text not null default 'DE',
  onboarding_completed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.scan_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  client_request_id uuid,
  scan_type text not null,
  barcode text,
  classification text,
  title text not null,
  subtitle text,
  summary text,
  confidence text,
  payload jsonb not null default '{}'::jsonb,
  is_public boolean not null default false,
  created_at timestamptz not null default now()
);
alter table public.scan_history
  add column if not exists client_request_id uuid,
  add column if not exists barcode text,
  add column if not exists classification text,
  add column if not exists summary text,
  add column if not exists confidence text,
  add column if not exists payload jsonb not null default '{}'::jsonb,
  add column if not exists is_public boolean not null default false;

create table if not exists public.product_favorites (
  user_id uuid not null references auth.users(id) on delete cascade,
  barcode text not null,
  scan_id bigint references public.scan_history(id) on delete set null,
  name text not null,
  status text not null,
  image_url text,
  reason text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  primary key (user_id,barcode)
);
alter table public.product_favorites
  add column if not exists scan_id bigint references public.scan_history(id) on delete set null,
  add column if not exists payload jsonb not null default '{}'::jsonb;

create table if not exists public.daily_scan_usage (
  usage_date date not null,
  subject_type text not null default 'user' check (subject_type='user'),
  subject_id text not null,
  used_count integer not null default 0 check (used_count>=0),
  updated_at timestamptz not null default now(),
  primary key (usage_date,subject_type,subject_id)
);

create unique index if not exists scan_history_user_request_unique
  on public.scan_history(user_id,client_request_id) where client_request_id is not null;
create index if not exists scan_history_user_created_idx
  on public.scan_history(user_id,created_at desc);
create index if not exists scan_history_user_type_idx
  on public.scan_history(user_id,scan_type);
create index if not exists scan_history_user_classification_idx
  on public.scan_history(user_id,classification);
create index if not exists product_favorites_user_created_idx
  on public.product_favorites(user_id,created_at desc);

alter table public.profiles enable row level security;
alter table public.user_preferences enable row level security;
alter table public.scan_history enable row level security;
alter table public.product_favorites enable row level security;
alter table public.daily_scan_usage enable row level security;

drop policy if exists "Public profiles are readable" on public.profiles;
drop policy if exists "Users read own profile" on public.profiles;
drop policy if exists "Users insert own profile" on public.profiles;
drop policy if exists "Users update own profile" on public.profiles;
drop policy if exists "Users delete own profile" on public.profiles;
create policy "Users read own profile" on public.profiles for select
  using (id=(select auth.uid()));
create policy "Users insert own profile" on public.profiles for insert
  with check (id=(select auth.uid()));
create policy "Users update own profile" on public.profiles for update
  using (id=(select auth.uid())) with check (id=(select auth.uid()));
create policy "Users delete own profile" on public.profiles for delete
  using (id=(select auth.uid()));

drop policy if exists "Users manage own preferences" on public.user_preferences;
create policy "Users manage own preferences" on public.user_preferences for all
  using (user_id=(select auth.uid())) with check (user_id=(select auth.uid()));

drop policy if exists "Users read own scans" on public.scan_history;
drop policy if exists "Users insert own scans" on public.scan_history;
drop policy if exists "Users update own scans" on public.scan_history;
drop policy if exists "Users delete own scans" on public.scan_history;
create policy "Users read own scans" on public.scan_history for select
  using (user_id=(select auth.uid()));
create policy "Users insert own scans" on public.scan_history for insert
  with check (user_id=(select auth.uid()));
create policy "Users update own scans" on public.scan_history for update
  using (user_id=(select auth.uid())) with check (user_id=(select auth.uid()));
create policy "Users delete own scans" on public.scan_history for delete
  using (user_id=(select auth.uid()));

drop policy if exists "Service role manages product favorites" on public.product_favorites;
drop policy if exists "Users read own product favorites" on public.product_favorites;
drop policy if exists "Users insert own product favorites" on public.product_favorites;
drop policy if exists "Users update own product favorites" on public.product_favorites;
drop policy if exists "Users delete own product favorites" on public.product_favorites;
create policy "Users read own product favorites" on public.product_favorites for select
  using (user_id=(select auth.uid()));
create policy "Users insert own product favorites" on public.product_favorites for insert
  with check (user_id=(select auth.uid()));
create policy "Users update own product favorites" on public.product_favorites for update
  using (user_id=(select auth.uid())) with check (user_id=(select auth.uid()));
create policy "Users delete own product favorites" on public.product_favorites for delete
  using (user_id=(select auth.uid()));

drop policy if exists "Service role manages scan usage" on public.daily_scan_usage;
create policy "Service role manages scan usage" on public.daily_scan_usage for all
  using (auth.role()='service_role') with check (auth.role()='service_role');

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values ('user-uploads','user-uploads',false,6291456,array['image/jpeg','image/png'])
on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,
  allowed_mime_types=excluded.allowed_mime_types;
drop policy if exists "Users read own uploads" on storage.objects;
drop policy if exists "Users insert own uploads" on storage.objects;
drop policy if exists "Users update own uploads" on storage.objects;
drop policy if exists "Users delete own uploads" on storage.objects;
create policy "Users read own uploads" on storage.objects for select to authenticated
  using (bucket_id='user-uploads' and (storage.foldername(name))[1]=(select auth.uid())::text);
create policy "Users insert own uploads" on storage.objects for insert to authenticated
  with check (bucket_id='user-uploads' and (storage.foldername(name))[1]=(select auth.uid())::text);
create policy "Users update own uploads" on storage.objects for update to authenticated
  using (bucket_id='user-uploads' and (storage.foldername(name))[1]=(select auth.uid())::text)
  with check (bucket_id='user-uploads' and (storage.foldername(name))[1]=(select auth.uid())::text);
create policy "Users delete own uploads" on storage.objects for delete to authenticated
  using (bucket_id='user-uploads' and (storage.foldername(name))[1]=(select auth.uid())::text);

create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path=public as $$
begin
  insert into public.profiles(id,email,profile_name,display_name)
  values(new.id,new.email,
    coalesce(new.raw_user_meta_data->>'profile_name',split_part(new.email,'@',1),'Veggie Nutzer'),
    coalesce(new.raw_user_meta_data->>'profile_name',split_part(new.email,'@',1),'Veggie Nutzer'))
  on conflict(id) do update set email=excluded.email;
  insert into public.user_preferences(user_id) values(new.id)
  on conflict(user_id) do nothing;
  return new;
end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute function public.handle_new_user();

commit;
