-- Canonical mobile Community-Spots schema. Safe to run repeatedly.
begin;

create table if not exists public.community_spots (
  id bigint generated by default as identity primary key,
  name text not null,
  place text not null,
  price text default 'Preis offen',
  status text not null check (status in ('vegan','vegetarisch','nicht veggie','vegan moeglich')),
  category text not null,
  lat double precision not null,
  lng double precision not null,
  description text not null,
  image_url text,
  created_by text,
  created_by_name text,
  is_public boolean not null default true,
  confirmations integer not null default 0,
  confirmed_at timestamptz default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.community_spots
  add column if not exists image_url text,
  add column if not exists created_by text,
  add column if not exists created_by_name text,
  add column if not exists is_public boolean not null default true,
  add column if not exists updated_at timestamptz not null default now();

create table if not exists public.spot_confirmations (
  spot_id bigint not null references public.community_spots(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (spot_id,user_id)
);

create table if not exists public.spot_reactions (
  id bigserial primary key,
  spot_id bigint not null references public.community_spots(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  reaction text not null check (reaction in ('like','dislike')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists community_spots_public_created_idx
  on public.community_spots(is_public,created_at desc);
create index if not exists community_spots_status_created_idx
  on public.community_spots(status,created_at desc);
create index if not exists community_spots_category_created_idx
  on public.community_spots(category,created_at desc);
create index if not exists community_spots_created_by_idx
  on public.community_spots(created_by);
create index if not exists community_spots_lat_lng_idx
  on public.community_spots(lat,lng);
create index if not exists spot_confirmations_user_idx
  on public.spot_confirmations(user_id,created_at desc);
create unique index if not exists spot_reactions_one_per_user
  on public.spot_reactions(spot_id,user_id);
create index if not exists spot_reactions_user_idx
  on public.spot_reactions(user_id,updated_at desc);

alter table public.community_spots enable row level security;
alter table public.spot_confirmations enable row level security;
alter table public.spot_reactions enable row level security;

drop policy if exists "Community spots are readable" on public.community_spots;
drop policy if exists "Published community spots are readable" on public.community_spots;
drop policy if exists "Users insert own community spots" on public.community_spots;
drop policy if exists "Users update own community spots" on public.community_spots;
drop policy if exists "Users delete own community spots" on public.community_spots;
create policy "Published community spots are readable" on public.community_spots for select
  using (is_public=true or created_by=(select auth.uid())::text);
create policy "Users insert own community spots" on public.community_spots for insert to authenticated
  with check (created_by=(select auth.uid())::text);
create policy "Users update own community spots" on public.community_spots for update to authenticated
  using (created_by=(select auth.uid())::text) with check (created_by=(select auth.uid())::text);
create policy "Users delete own community spots" on public.community_spots for delete to authenticated
  using (created_by=(select auth.uid())::text);

drop policy if exists "Users read own spot confirmations" on public.spot_confirmations;
drop policy if exists "Users insert own spot confirmations" on public.spot_confirmations;
drop policy if exists "Service role manages spot confirmations" on public.spot_confirmations;
create policy "Users read own spot confirmations" on public.spot_confirmations for select
  using (user_id=(select auth.uid()));
create policy "Users insert own spot confirmations" on public.spot_confirmations for insert
  with check (user_id=(select auth.uid()));
create policy "Service role manages spot confirmations" on public.spot_confirmations for all
  using (auth.role()='service_role') with check (auth.role()='service_role');

drop policy if exists "spot reactions are readable" on public.spot_reactions;
drop policy if exists "spot reactions are written by service role" on public.spot_reactions;
create policy "spot reactions are readable" on public.spot_reactions for select using (true);
create policy "spot reactions are written by service role" on public.spot_reactions for all
  using (auth.role()='service_role') with check (auth.role()='service_role');

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values ('community-spot-images','community-spot-images',true,6291456,array['image/jpeg','image/png'])
on conflict(id) do update set public=true,file_size_limit=excluded.file_size_limit,
  allowed_mime_types=excluded.allowed_mime_types;
drop policy if exists "Public reads community spot images" on storage.objects;
drop policy if exists "Users insert own community spot images" on storage.objects;
drop policy if exists "Users update own community spot images" on storage.objects;
drop policy if exists "Users delete own community spot images" on storage.objects;
create policy "Public reads community spot images" on storage.objects for select
  using (bucket_id='community-spot-images');
create policy "Users insert own community spot images" on storage.objects for insert to authenticated
  with check (bucket_id='community-spot-images' and (storage.foldername(name))[1]=(select auth.uid())::text);
create policy "Users update own community spot images" on storage.objects for update to authenticated
  using (bucket_id='community-spot-images' and (storage.foldername(name))[1]=(select auth.uid())::text)
  with check (bucket_id='community-spot-images' and (storage.foldername(name))[1]=(select auth.uid())::text);
create policy "Users delete own community spot images" on storage.objects for delete to authenticated
  using (bucket_id='community-spot-images' and (storage.foldername(name))[1]=(select auth.uid())::text);

commit;
