create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  profile_name text not null,
  avatar_url text,
  public_spots boolean not null default true,
  public_scans boolean not null default false,
  public_comments boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.community_spots
add column if not exists is_public boolean not null default true;

create table if not exists public.scan_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  scan_type text not null,
  title text not null,
  subtitle text,
  payload jsonb not null default '{}'::jsonb,
  is_public boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.spot_comments (
  id bigint generated by default as identity primary key,
  spot_id bigint not null references public.community_spots(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  author_name text not null,
  body text not null,
  is_public boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.scan_history enable row level security;
alter table public.spot_comments enable row level security;

create policy "Public profiles are readable"
  on public.profiles
  for select
  using (true);

create policy "Users update own profile"
  on public.profiles
  for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

create policy "Users read own scans"
  on public.scan_history
  for select
  using (auth.uid() = user_id or is_public = true);

create policy "Users insert own scans"
  on public.scan_history
  for insert
  with check (auth.uid() = user_id);

create policy "Public comments are readable"
  on public.spot_comments
  for select
  using (is_public = true);

create policy "Users insert own comments"
  on public.spot_comments
  for insert
  with check (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, profile_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'profile_name', new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', split_part(new.email, '@', 1), 'Veggie Nutzer')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();
