create table if not exists public.community_spots (
  id bigint generated by default as identity primary key,
  name text not null,
  place text not null,
  price text default 'Preis offen',
  status text not null check (status in ('vegan', 'vegetarisch', 'nicht veggie', 'vegan moeglich')),
  category text not null,
  rating text default 'neu',
  lat double precision not null,
  lng double precision not null,
  description text not null,
  image_data_url text,
  confirmations integer not null default 0,
  confirmed_at timestamptz default now(),
  created_at timestamptz not null default now()
);

alter table public.community_spots enable row level security;

create policy "Community spots are readable"
  on public.community_spots
  for select
  using (true);
